### ISSUE TITLE
How to Register the DataSet

### ISSUE THREAD

**Issue by zhijiejia** [ethanweber/xview2#5]
The correct step is the follows after sucessfully install detectron2 and xBD dataset ?
1. crop the xBD dataset, make each one original image from 1 * 1024 * 1024 to 4 * 512 * 512
2. register the dataset that from step 1

But Can you describe how to Register the dataset ??  I am a Vegetable chicken...

**Comment by ethanweber** [comment]
Hello @zhijiejia, can you check Issue #4 to see if that helps? Thanks!

**Comment by zhijiejia** [comment]
Hey, I find I git clone the facebookresearch/detectron2 rather than ethanweber/detectron2， but I can't pip install the package from ethanweber/detectron2 and I successfully installed the package from facebookresearch/detectron2, the error info I will show the next comment.

**Comment by zhijiejia** [comment]
![Uploading image.png…]()

**Comment by ethanweber** [comment]
Could you reupload the image if you are still having troubles? I don't think I fully understand the problem yet. Thanks!

**Comment by zyp-zhangyuping** [comment]
Hello, there is an error of “”KeyError: "Dataset 'xview_semantic_damage_quad_train' is not registered!“” when running the code.I want to ask how to register a data set and use the xview data set to run through the code。Thank you very much

**Comment by ethanweber** [comment]
Hi, you can take a look at Issue #4 for help on this.
